import turtle

def draw_desk():
    # 创建一个海龟对象，用于绘制
    t = turtle.Turtle()

    # 设置绘制速度和粗细
    t.speed(10)
    t.pensize(3)

    # 绘制书桌的腿
    t.penup()
    t.goto(0, -20)
    t.pendown()
    t.setheading(-90)
    t.forward(170)
    t.setheading(15)
    t.forward(20)
    t.setheading(90)
    t.forward(168)
    t.backward(168)
    t.setheading(-165)
    t.forward(20)
    t.setheading(165)
    t.forward(20)
    t.setheading(90)
    t.forward(168)

    t.penup()
    t.goto(120, 10)
    t.pendown()
    t.setheading(-90)
    t.forward(170)
    t.setheading(15)
    t.forward(20)
    t.setheading(90)
    t.forward(168)
    t.backward(168)
    t.setheading(-165)
    t.forward(20)
    t.setheading(165)
    t.forward(20)
    t.setheading(90)
    t.forward(166)

    t.penup()
    t.goto(-120, 10)
    t.pendown()
    t.setheading(-90)
    t.forward(170)
    t.setheading(15)
    t.forward(20)
    t.setheading(90)
    t.forward(168)
    t.backward(168)
    t.setheading(-165)
    t.forward(20)
    t.setheading(165)
    t.forward(20)
    t.setheading(90)
    t.forward(170)

    # 绘制书桌的桌面
    t.color("brown")
    t.fillcolor("white")
    t.penup()
    t.goto(0, 0)
    t.pendown()
    t.begin_fill()
    t.setheading(15)
    t.forward(150)
    t.setheading(165)
    t.forward(150)
    t.setheading(-165)
    t.forward(150)
    t.setheading(-15)
    t.forward(150)
    t.setheading(15)
    t.forward(150)
    t.setheading(-90)
    t.forward(20)
    t.setheading(-165)
    t.forward(150)
    t.setheading(165)
    t.forward(150)
    t.setheading(90)
    t.forward(20)
    t.end_fill()

    # 隐藏海龟并显示绘画结果
    turtle.done()

draw_desk()